services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=${TZ}
      - PORT=${SEERR_PORT}
    ports:
      - ${ARC_BIND_IP:-0.0.0.0}:5055:${SEERR_PORT}
    volumes:
      - /docker/config/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    init: true
